### ISSUE TITLE
Crash on API 27

### ISSUE THREAD

**Issue by rutvikwebmobtech** [pathsense/pathsense-samples-android#15]
`android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=-2 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                               at android.os.Looper.loop(Looper.java:164)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by rutvikwebmobtech** [comment]
NO reply from developers... @PaulSchmitt @dfinlay @ptenereillo @dyerjo @pablobaxter  Pathsense SDK removed from my project. Thank you for your great support.

**Comment by dyerjo** [comment]
This error has been fixed on the latest release. Please, update to PathSense Android SDK 3.1.0.6.
