### ISSUE TITLE
java.lang.IllegalArgumentException: provider doesn't exist: network

### ISSUE THREAD

**Issue by harcoPro** [pathsense/pathsense-samples-android#4]
Android: 6.0
Android Build: EMUI4.0_H60-L02_6.5.1
Manufacturer: HUAWEI
Model: H60-L02
Thread: main-1

java.lang.IllegalArgumentException: provider doesn't exist: network
    at android.os.Parcel.readException(Parcel.java:1606)
    at android.os.Parcel.readException(Parcel.java:1555)
    at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:606)
    at android.location.LocationManager.requestLocationUpdates(LocationManager.java:880)
    at android.location.LocationManager.requestLocationUpdates(LocationManager.java:464)
    at com.pathsense.locationengine.apklib.data.k.handleMessage(Unknown Source)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:150)
    at android.app.ActivityThread.main(ActivityThread.java:5546)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by dyerjo** [comment]
Hi, 

What version of the SDK did you experience this on? 

Thank you.

**Comment by pablobaxter** [comment]
Fixed as of 2.1.0.0
